[toolchain]
anchor_version = "0.28.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
on_chain_trading_bot = "3seUuDx9nQXF18sEtcyZBkrf4YQjxHJuYFS26JVn1ERK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
