[workspace]
members = [
    "programs/*"
]

resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
opt-level = 3
incremental = false

[workspace.dependencies]
solana-program = "=2.1.0"
anchor-lang = "0.30.1"
borsh = "=1.5.1"  # Pin to specific version
